<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="5" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="232" started-at="2018-09-09T06:35:54Z" finished-at="2018-09-09T06:35:55Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="232" started-at="2018-09-09T06:35:54Z" finished-at="2018-09-09T06:35:55Z">
      <class name="Jenkins.com.jenkins.TestClass1">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:Jenkins.com.jenkins.TestClass1@29774679]" name="beforeClass" is-config="true" duration-ms="32" started-at="2018-09-09T06:35:54Z" finished-at="2018-09-09T06:35:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="TC_1()[pri:0, instance:Jenkins.com.jenkins.TestClass1@29774679]" name="TC_1" duration-ms="20" started-at="2018-09-09T06:35:55Z" finished-at="2018-09-09T06:35:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_1 -->
        <test-method status="PASS" signature="TC_2()[pri:0, instance:Jenkins.com.jenkins.TestClass1@29774679]" name="TC_2" duration-ms="4" started-at="2018-09-09T06:35:55Z" finished-at="2018-09-09T06:35:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_2 -->
        <test-method status="PASS" signature="TC_3()[pri:0, instance:Jenkins.com.jenkins.TestClass1@29774679]" name="TC_3" duration-ms="4" started-at="2018-09-09T06:35:55Z" finished-at="2018-09-09T06:35:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_3 -->
        <test-method status="PASS" signature="TC_4()[pri:0, instance:Jenkins.com.jenkins.TestClass1@29774679]" name="TC_4" duration-ms="16" started-at="2018-09-09T06:35:55Z" finished-at="2018-09-09T06:35:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_4 -->
        <test-method status="FAIL" signature="TC_5()[pri:0, instance:Jenkins.com.jenkins.TestClass1@29774679]" name="TC_5" duration-ms="8" started-at="2018-09-09T06:35:55Z" finished-at="2018-09-09T06:35:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at Jenkins.com.jenkins.TestClass1.TC_5(TestClass1.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_5 -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:Jenkins.com.jenkins.TestClass1@29774679]" name="afterClass" is-config="true" duration-ms="8" started-at="2018-09-09T06:35:55Z" finished-at="2018-09-09T06:35:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- Jenkins.com.jenkins.TestClass1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
